/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3ESOUNDPOOL_AUTODEFS_H
#define S3ESOUNDPOOL_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_SOUNDPOOL_NAME "s3eSoundPool"
#define S3E_EXT_SOUNDPOOL_HASH 0x7a514333

#endif /* !S3ESOUNDPOOL_AUTODEFS_H */
